### ISSUE TITLE
rdk init fails when AWS Config is configured to use a bucket from another account

### ISSUE THREAD

**Issue by StefanKrecher** [awslabs/aws-config-rdk#123]
rdk init seems to fail, when delivery_channels['DeliveryChannels'][0]['s3BucketName'] returns the name of a central bucket from another account. The init-process isn't aware that the bucket already exists (maybe it is enough to set "config_bucket_exists = True" at around line 118/119).
Anyway: the call "response = my_s3.list_buckets()" will not return the name of the bucket (because the bucket is in another account).
The then following create_bucket account will fail, because the bucket-name isn't available

_Originally posted by @StefanKrecher in https://github.com/awslabs/aws-config-rdk/issues/46#issuecomment-436213321_

**Comment by StefanKrecher** [comment]
This is a bug.
Adding:
config_bucket_exists = True
after line 118 solved the problem for me

**Comment by vikas027** [comment]
Hey @StefanKrecher ,

Where have you specified the line `config_bucket_exists = True`?

**Comment by bkrodgers** [comment]
Any updates on this?  It looks like you can work around this for the most part if you manually create the bucket it wants you to use for deploying the rules, but the failed rdk init appears to mean that bucket isn't created in the init process.

(FWIW, ran into this in a workshop at re:Inforce)

**Comment by jack1902** [comment]
i could add an additional arg to the init parser so that you can state the bucket already exists at the command line? 

`parser.add_argument('--config_bucket_exists_in_another_account', required=False, action='store_true', help='[optional] remove config bucket check')`

This would simply skip the bucket step but still check everything else, could even update the error message when this flag isn't passed so that it asks does the bucket exist in another account if so, pass the above flag.

Let me know, i really like this command-line tool and want to improve it :)

**Comment by darrent** [comment]
Hi, would it be fair to say that the only way to currently run the **init** command is to pull the rdk source code, configure `config_bucket_exists = True`, build and use?

**Comment by jack1902** [comment]
@darrent if you want to run the init but essentially skip bucket creation you can pull down my PR to skip checking the bucket but still get all the other checks done

**Comment by 0xjjoyy** [comment]
Hi, any updates on this issue?
