### ISSUE TITLE
Add support for multi-account deployment through organizations

### ISSUE THREAD

**Issue by djschnei21** [awslabs/aws-config-rdk#182]
rdk should support the OrganizationConfigRule api set.  This would negate the need to "rdk create-rule-template" when people have an organization enabled.  Deploy to master account, rule would end up in all member accounts automatically.  
https://docs.aws.amazon.com/config/latest/developerguide/config-rule-multi-account-deployment.html

**Comment by aidansteele** [comment]
I don't mean to seem impatient, but is there any movement on this? It's been just over a year and I'm wondering if I can use the Config RDK to author "organization config rules".

**Comment by jack1902** [comment]
@aidansteele have a look at: https://github.com/awslabs/aws-config-engine-for-compliance-as-code

But in truth once you have the boiler plate code extracted to a module (the bit that does the talking to aws config) this repo is not that useful

**Comment by aidansteele** [comment]
Thanks @jack1902 for the insanely quick and very helpful response, that clears it up! I've had a look through that repo (and the `Version2` branch) and it answered the questions I had. 

For posterity: I wanted to know how the Lambda function in the compliance account gains access to the application accounts in order to describe, list, get, etc. resources. It looks like the answer is that the solution deploys a role in all the application accounts with a trust policy that [allows it to be assumed by `config.amazonaws.com` _and_ the compliance Lambda](https://github.com/awslabs/aws-config-engine-for-compliance-as-code/blob/4de3617a4000361c4f2d5c9da1c634ceec61aad8/application-account-iam.yaml#L132-L140). Which I guess makes sense! It also provided very helpful diagrams that indicated that `PutEvaluations` is called in the application accounts.

**Comment by jack1902** [comment]
You are right on the trust relationship, also, for future reference if you have any issues with the RDK i actually find it quicker to email the team at AWS directly rdk-maintainers@amazon.com . Its how i found out about the link i gave above and thought i'd share the knowledge

**Comment by bmorrissirromb** [comment]
I think this issue has been resolved so I'll be closing it. Two more notes for posterity in case anyone comes across this discussion:

1. [This blog post](https://aws.amazon.com/blogs/mt/deploying-custom-aws-config-rules-in-an-aws-organization-environment/) does a good job of walking through deploying rdk rules to an Organization.
2. rdk's `deploy-organization` command is very useful for rdk Organization-wide deploys.
