### ISSUE TITLE
Sample CI for AWS::SSM::ManagedInstanceInventory

### ISSUE THREAD

**Issue by ashishpujari** [awslabs/aws-config-rdk#185]
No sample CI found for AWS::SSM::ManagedInstanceInventory, even though it appears to be a supported CI.

**Comment by bmorrissirromb** [comment]
This CI exists, but has some issues due to the differences with newlines in Windows vs Linux. If you just need a reference, feel free to look at the file directly: https://github.com/awslabs/aws-config-rdk/blob/master/rdk/template/example_ci/AWS_SSM_ManagedInstanceInventory.json

I am going to look at what it takes to make this work in both Windows and Linux.
