### ISSUE TITLE
Too many rules, reaching CloudFormation 51200 Char Limit

### ISSUE THREAD

**Issue by ivanfuglo** [awslabs/aws-config-rdk#247]
We have recently started getting the following error when trying to deploy Config rules:
` at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200 `
It seems that we have too many rules so the CloudFormation template is too long. We currently have ~45 rules going to the same account.
Would it be possible to detect the character length and split to multiple stacks? Any other ways to work around this?

**Comment by jongogogo** [comment]
First band-aid: upload your stack into S3, and deploy from there, you will have 3 times to size limit. Other way to improve is to work with the new Conformance Packs, which are little bit less wordy.

I like the idea to have multiple stack generated @rickychau2780

**Comment by ivanfuglo** [comment]
@rickychau2780 this is the full trace that it logs per account. The error appears in Compliance-Rule-Template-Deploy CodeBuild project.

```Start rules deployment on account XXXXXXXXXXXX for region <region>.
Attempting to update Rule stack.
Error no condition matched: An error occurred (ValidationError) when calling the UpdateStack operation: 1 validation error detected: Value '<Dump of the entire stack, 57,799 characters total>' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
arn:aws:config:<region>:XXXXXXXXXXXX:config-rule/config-rule-abcdef
Adding following tags to <Rule Name> in account XXXXXXXXXXXX
[{'Key': 'xxxx', 'Value': 'yyyy'}, {'Key': 'aaaa', 'Value': 'bbbb'}]```

Thanks!

**Comment by rickychau2780** [comment]
@ivanfuglo that is an issue on compliance engine, https://github.com/awslabs/aws-config-engine-for-compliance-as-code. As @jongogogo suggest, in rulesets-build/deploy_rule_templates.py, instead of using TemplateBody for update_stack, you can 
1. upload the template to s3 in a bucket in targeting account (best practice is add the bucket creation in application-account-initial-setup.yaml)
2. get the s3url for the template
3. use TemplateURL for update_stack

I have tried generating a presigned URL for TemplateURL to avoid uploading the same template to targeting account but cloudformation does not supporting it. 

Another alternative is grant application account Config role cross account access to the template stored in centralized account.

**Comment by ivanfuglo** [comment]
@rickychau2780 Thanks! I went with your last suggestion and actually started it a few days ago. It was not too bad to implement. The most challenging part was dynamically updating the bucket policy and KMS key policy to allow all application accounts to read from the bucket when they update the stack. Anyway, Thanks for responding and I will close this here.
