### ISSUE TITLE
Official documentation site

### ISSUE THREAD

**Issue by aurelienmarie** [awslabs/aws-config-rdk#317]
The [documentation](https://rdk.readthedocs.io/en/latest/index.html) points to a fork which looks less maintained than this official repository. As it's referenced on official [AWS workshop](https://controltower.aws-management.tools/security/config/), it might be useful to point to an official maintained repository.

**Comment by bmorrissirromb** [comment]
@michaelborchert - Are you able to change the RDK ReadTheDocs to point at the `awslabs`-owned RDK repo, instead of your fork?

**Comment by bmorrissirromb** [comment]
The better read-the-docs link is here: https://aws-config-rdk.readthedocs.io/en/master/

The `rdk.readthedocs.io` page was set up by @michaelborchert and is no longer actively maintained.

I'll look into having the AWS workshop point at the preferred documentation.

**Comment by bmorrissirromb** [comment]
I've reached out to the CT team to make the update.

Also worth noting: the latest version of the CT workshop is here now: https://catalog.workshops.aws/control-tower/en-US

**Comment by bmorrissirromb** [comment]
I'm continuing to chase down leads on this

**Comment by bmorrissirromb** [comment]
That CT workshop site will be updated soon, just got the MR into their repo.

For clarity: https://aws-config-rdk.readthedocs.io/en/master/ is the good, newer documentation repo.

The https://rdk.readthedocs.io/en/latest/index.html site is an old cut of documentation from several years ago. I'm working to chase down its owner and have them archive it. But since that's not something I have control over, I'm going to close this issue.
