### ISSUE TITLE
Create Rules Issue

### ISSUE THREAD

**Issue by stevenruizhang** [awslabs/aws-config-rdk#455]
When i use Create Rules command line in win 11 i get below issue even escape the double-quotes when specifying input parameters,

![image](https://github.com/awslabs/aws-config-rdk/assets/13114985/9cf543da-5f17-4084-9a65-1ab19af5055b)

**Comment by bmorrissirromb** [comment]
Howdy -- Looks like you're using the PowerShell escaping syntax but in cmd.exe.

The cmd syntax is more like:
`rdk create MyRule --runtime python3.11 --resource-types AWS::EC2::Instance --input-parameters "{""desiredInstanceType"":""t2.micro""}"`

Alternatively, you could use PowerShell and keep your current command.

Also, you may need to install the latest version of RDK (0.17.1) in order to use the Python 3.11 runtime.
