### ISSUE TITLE
Add support for central Config bucket

### ISSUE THREAD

**Issue by michaelborchert** [awslabs/aws-config-rdk#46]
Add a flag to allow `init` to ignore missing Config bucket, for the use case where a central bucket in a separate account is being used to track Configuration history.

**Comment by StefanKrecher** [comment]
This is important, since init seems to fail, when  delivery_channels['DeliveryChannels'][0]['s3BucketName'] returns the name of a central bucket from another account. The init-process isn't aware that the bucket already exists (maybe it is enough to set "config_bucket_exists = True" at around line 118/119).
Anyway: the call "response = my_s3.list_buckets()" will not return the name of the bucket (because the bucket is in another account).
The then following create_bucket account will fail, because the bucket-name isn't available

**Comment by jack1902** [comment]
This issue should be closed as there is now a flag for this
