### ISSUE TITLE
Config-RDK and eliminating old lambda versions

### ISSUE THREAD

**Issue by Distroyed** [awslabs/aws-config-rdk#471]
This is my first time posting here , I am also new to AWS Cloud development (super green) so please be gentle.

I am currently using config-rdk to create lambda functions for config rules.  Since this is being done outside of IAC we have discovered this is causing a huge build up of old lambda versions being created.  This is setting off our Trusted Advisor alerts as over the years these versions have piled up.

So now we are having to create a python script for clean up, but this does not solve the problem of preventing this from happening right at the source.

The goal of this post, and I have hopefully crafted it so it make sense, is to prevent config-rdk from creating multiple versions of the lambda every time codebuild is executed due to a change to the lambda function.

**Comment by bmorrissirromb** [comment]
It's an interesting idea, but I'm not sure any alternative would make sense.

1. Versions allow for updating the code in-place instead of the alternative where you destroy and re-create a new Lambda each time.
2. With the dependencies involved, that probably also means creating a new Config rule each time, and a loss of any history/evaluations from that rule.
3. Versions also give you a little more historical context about how the rule used to be evaluated.
4. They're also cheap -- there's very little downside to having old rule versions around in my opinion, though I'd be interested in hearing what Trusted Advisor has to say on this matter.

Do you change the Lambda function code frequently enough that you have a lot of versions created? In my experience, Config rules don't change *that* much.
