### ISSUE TITLE
Add a delete function to clean up enviroment

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#48]
Useful for doing automated testing

**Comment by devopsdream** [comment]
Any status on this issue?

**Comment by michaelborchert** [comment]
I've been thinking about implementation, and will try to get to it this week or weekend.  I think what's actually needed is an "undeploy" that deletes the CFN template that was used to deploy a single rule using the `deploy` command, and doesn't actually delete anything on your local filesystem.

This feature request is made a little bit more complex by the new --functions-only option for deploy, since it deploys all of the Lambda functions as a single CFN template.  I suspect that the best way to handle that is to simply throw an error message if there is no individual function+config rule CFN template deployed and in the error message mention that Lambda functions deployed via the --functions-only option will not be cleaned up.  If there are other suggestions on how to handle this case I would love to hear them!

**Comment by jongogogo** [comment]
It would need to clean up the rdk init as well.

**Comment by jongogogo** [comment]
@michaelborchert on your comment on the function-only. I would imagine a something to check the all CFn patterns the rdk deploys and delete them all.

**Comment by michaelborchert** [comment]
The --rules-only deployment lets you specify a stackname to override the
default so we won't be able to 100% guarantee the account gets cleaned up.
Though if you've used the stackname override then you can just use the aws
cli to delete the stack.

**Comment by jongogogo** [comment]
Is the stackname override be prefixed by a known pattern? Not sure what is drinving this feature of Stack name override.

**Comment by michaelborchert** [comment]
It is to allow independent management of Lambda functions by ruleset.  If RDK only used a single name for the Lambda function stack subsequent deploys of different rulesets or rules with the --functions-only flag would necessarily overwrite the previous deployment, which I don't think is the desired behavior by anyone.

In general I am trying to avoid directly duplicating functionality with the AWS CLI, is there a reason

$ rdk deploy --functions-only --stack-name my-function-stack <rule identifiers>
< do whatever testing you want >
$ aws cloudformation delete-stack --stack-name my-function-stack

is insufficient?  Again, I'm fine with adding an `undeploy` command to delete the per-rule stacks because the RDK is completely managing the naming and I think that'll be how most people are doing testing so it makes sense to me to support that in the RDK workflow.  This would be _only_ for --functions-only deployments, which are intended for an enterprise multi-account setup deployment.

**Comment by michaelborchert** [comment]
I have been thinking about this, and from the conversation above it sounds like there are two use cases that need to be supported:
1) Remove a Rule from an environment, to be used for cleaning up after automated testing of a single Rule or cost reduction
2) Scrub an AWS Account clean of RDK-deployed resources and configuration to clean up after automated testing of end-to-end deployment automation.

I think what's needed is actually two new commands:
1) "undeploy" which removes a deployed rule that has been deployed the "classic" way without using --functions-only.  This would simply delete the CFN template for the specific Rule and would be used for testing individual rules.
2) "clean" which would completely remove all Rules, as well as remove any RDK-managed S3 buckets and IAM resources, as well as the configuration recorder and delivery channel.  This would be used for testing more complex CI/CD pipelines and multi-account deployments, and would satisfy jongogo's added requirements from July 17th.

If that all makes sense I can split off a second issue for the `clean` command.

**Comment by michaelborchert** [comment]
I've added #2 from above as part of PR #82.

**Comment by michaelborchert** [comment]
And now item #1 has been address by PR #83.  A new version has been pushed to pypi.  Thanks!
