### ISSUE TITLE
Support for ARM/Graviton lambda runtime

### ISSUE THREAD

**Issue by guardbadger** [awslabs/aws-config-rdk#487]
Hi,

It would be good to be able to move the RDK rules to support ARM64 runtimes.

Thanks

Steve

**Comment by bmorrissirromb** [comment]
I'm not sure what the ask here is. RDK is pretty firmly in the "Python-only" camp nowadays. We had previously supported Java rules, but those were not particularly popular with the community.

But in any case, ARM/Graviton aren't _runtimes_. They're architectures. If you're writing your RDK rules in Python, the chipset used to run the instructions should be totally abstracted so that you don't need to care about it. Config rules also aren't the type of computation where ultra-high-performance is necessary.

All that to say: I'm inclined to close this issue unless there's a clearer use case defined.
